name: tamil_manthar
description: தமிழ் மாந்தர் - திறன் பார்வை. Offline Tamil OCR Android app.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  image: ^4.2.0
  flutter_tesseract_ocr: ^0.4.31

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tessdata/
